# Generated by Django 4.2.10 on 2024-02-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_index', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Atividade',
        ),
        migrations.RenameField(
            model_name='integrantes',
            old_name='funcao',
            new_name='cargo',
        ),
        migrations.AddField(
            model_name='integrantes',
            name='CPF',
            field=models.IntegerField(blank=True, help_text='apenas numeros', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='integrantes',
            name='RA',
            field=models.IntegerField(blank=True, help_text='apenas numeros', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='integrantes',
            name='RG',
            field=models.IntegerField(blank=True, help_text='apenas numeros', max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='integrantes',
            name='ativo',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='integrantes',
            name='curso',
            field=models.CharField(choices=[('AD', 'Análise e Desenvolvimento de Sistemas'), ('AU', 'Automação Industrial'), ('CC', 'Ciência da Computação'), ('EB', 'Engenharia de Bio. e Biotec.'), ('EL', 'Engenharia Elétrica'), ('MC', 'Engenharia Mecânica'), ('QM', 'Engenharia Química'), ('EP', 'Engenharia de Produção'), ('FM', 'Fabricação Mecânica')], default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='integrantes',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='integrantes',
            name='area',
            field=models.CharField(choices=[('Aerodinâmica', 'Aerodinâmica'), ('Direção', 'Direção e Suspenção'), ('Elétrica', 'Elétrica'), ('Estrutura', 'Estrutura'), ('Freio e Ergonomia', 'Freio e Ergonomia'), ('Powewtrain', 'Powewtrain'), ('Comercial', 'Comercial'), ('Financeiro', 'Financeiro'), ('Gestão', 'Gestão de Pessoas'), ('Marketing', 'Marketing'), ('Qualidade', 'Qualidade'), ('NA', 'Nenhuma')], max_length=50),
        ),
        migrations.AlterField(
            model_name='objetivosarea',
            name='area',
            field=models.CharField(choices=[('Aerodinâmica', 'Aerodinâmica'), ('Direção', 'Direção e Suspenção'), ('Elétrica', 'Elétrica'), ('Estrutura', 'Estrutura'), ('Freio e Ergonomia', 'Freio e Ergonomia'), ('Powewtrain', 'Powewtrain'), ('Comercial', 'Comercial'), ('Financeiro', 'Financeiro'), ('Gestão', 'Gestão de Pessoas'), ('Marketing', 'Marketing'), ('Qualidade', 'Qualidade'), ('NA', 'Nenhuma')], default='Nenhuma', max_length=50),
        ),
    ]
