# Generated by Django 4.2.10 on 2024-02-29 11:14

from django.db import migrations, models
import pictures.models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_index', '0002_delete_atividade_rename_funcao_integrantes_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrantes',
            name='foto',
            field=pictures.models.PictureField(aspect_ratios=[None], blank=True, breakpoints={'l': 1200, 'm': 992, 's': 768, 'xl': 1400, 'xs': 576}, container_width=1200, file_types=['WEBP'], grid_columns=12, height_field=70, null=True, pixel_densities=[1, 2], upload_to='Integrantes', width_field=70),
        ),
        migrations.AlterField(
            model_name='integrantes',
            name='CPF',
            field=models.IntegerField(blank=True, help_text='apenas numeros', null=True),
        ),
        migrations.AlterField(
            model_name='integrantes',
            name='RA',
            field=models.IntegerField(blank=True, help_text='apenas numeros', null=True),
        ),
        migrations.AlterField(
            model_name='integrantes',
            name='RG',
            field=models.IntegerField(blank=True, help_text='apenas numeros', null=True),
        ),
        migrations.AlterField(
            model_name='integrantes',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
