# Generated by Django 4.2.10 on 2024-02-29 12:02

from django.db import migrations, models
import pictures.models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_index', '0005_alter_integrantes_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('picture', pictures.models.PictureField(aspect_ratios=[None], breakpoints={'l': 1200, 'm': 992, 's': 768, 'xl': 1400, 'xs': 576}, container_width=1200, file_types=['WEBP'], grid_columns=12, pixel_densities=[1, 2], upload_to='avatars')),
            ],
        ),
    ]
