# Generated by Django 4.2.10 on 2024-03-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_index', '0008_prazos_alter_integrantes_area_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prazos',
            options={'verbose_name': 'Prazo', 'verbose_name_plural': 'Prazos'},
        ),
        migrations.AddField(
            model_name='prazos',
            name='dias_restantes',
            field=models.DateField(blank=True, null=True),
        ),
    ]
