# Generated by Django 4.2.10 on 2024-03-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_index', '0009_alter_prazos_options_prazos_dias_restantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='prazos',
            name='atual',
            field=models.DateField(auto_now=True),
        ),
    ]
