# Generated by Django 4.2.10 on 2024-03-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_index', '0010_prazos_atual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prazos',
            name='dias_restantes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
