# Generated by Django 4.2.10 on 2024-03-01 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash_index', '0011_alter_prazos_dias_restantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prazos',
            name='atual',
        ),
        migrations.RemoveField(
            model_name='prazos',
            name='dias_restantes',
        ),
    ]
