# Generated by Django 4.2.10 on 2024-03-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_index', '0012_remove_prazos_atual_remove_prazos_dias_restantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='prazos',
            name='dias_restantes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
