# Generated by Django 4.2.10 on 2024-02-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade_Gantt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('Aerodinâmica', 'Aerodinâmica'), ('Direção', 'Direção e Suspenção'), ('Elétrica', 'Elétrica'), ('Estrutura', 'Estrutura'), ('Freio e Ergonomia', 'Freio e Ergonomia'), ('Powewtrain', 'Powewtrain'), ('Comercial', 'Comercial'), ('Financeiro', 'Financeiro'), ('Gestão', 'Gestão de Pessoas'), ('Marketing', 'Marketing'), ('NA', 'Nenhuma')], max_length=100)),
                ('atividade', models.CharField(max_length=50)),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField()),
                ('situacao', models.IntegerField(max_length=10)),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
            },
        ),
    ]
