# Generated by Django 4.2.10 on 2024-02-20 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade_gantt',
            name='data_final',
        ),
        migrations.RemoveField(
            model_name='atividade_gantt',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='atividade_gantt',
            name='situacao',
        ),
        migrations.CreateModel(
            name='Sub_Atividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_atividade', models.CharField(max_length=300)),
                ('situacao', models.CharField(choices=[('AF', 'A fazer'), ('FA', 'Fazendo'), ('FE', 'Feito')], max_length=100)),
                ('custo', models.DecimalField(decimal_places=2, max_digits=9)),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField()),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planejamento.atividade_gantt')),
            ],
            options={
                'verbose_name': 'Sub_Atividade',
                'verbose_name_plural': 'Sub_Atividades',
            },
        ),
    ]
