# Generated by Django 4.2.10 on 2024-02-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0002_remove_atividade_gantt_data_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade_gantt',
            name='data_final',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='atividade_gantt',
            name='data_inicio',
            field=models.DateField(null=True),
        ),
    ]
