# Generated by Django 4.2.10 on 2024-02-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0003_atividade_gantt_data_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_atividades',
            name='area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='atividade_gantt',
            name='data_final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atividade_gantt',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sub_atividades',
            name='situacao',
            field=models.CharField(choices=[('AF', 'A fazer'), ('FA', 'Fazendo'), ('FE', 'Feito')], default=0, max_length=100),
        ),
    ]
