# Generated by Django 4.2.10 on 2024-02-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0004_sub_atividades_area_alter_atividade_gantt_data_final_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gantt_Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=300)),
                ('recurso', models.CharField(max_length=300)),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField()),
                ('percent_complete', models.IntegerField()),
                ('dependencia', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='atividade_gantt',
            name='area',
            field=models.CharField(choices=[('Aerodinamica', 'Aerodinâmica'), ('Direcao', 'Direção e Suspenção'), ('Eletrica', 'Elétrica'), ('Estrutura', 'Estrutura'), ('Freio e Ergonomia', 'Freio e Ergonomia'), ('Powewtrain', 'Powewtrain'), ('Comercial', 'Comercial'), ('Financeiro', 'Financeiro'), ('Gestão', 'Gestão de Pessoas'), ('Marketing', 'Marketing'), ('Qualidade', 'Qualidade'), ('NA', 'Nenhuma')], max_length=100),
        ),
    ]
