# Generated by Django 4.2.10 on 2024-02-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0005_gantt_chart_alter_atividade_gantt_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='gantt_chart',
            name='area',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='gantt_chart',
            name='is_atividade',
            field=models.BooleanField(default=False),
        ),
    ]
