# Generated by Django 4.2.10 on 2024-02-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0006_gantt_chart_area_gantt_chart_is_atividade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gantt_chart',
            name='data_final',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='gantt_chart',
            name='data_inicio',
            field=models.DateField(null=True),
        ),
    ]
