# Generated by Django 4.2.10 on 2024-02-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0007_alter_gantt_chart_data_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade_gantt',
            name='situacao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
