# Generated by Django 4.2.10 on 2024-02-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0010_alter_gantt_chart_percent_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='gantt_chart',
            name='inicio_atividade',
            field=models.DateField(null=True),
        ),
    ]
